apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "employee-api.name" . }}-config
  namespace: {{ .Values.namespace.name }}
data:
  {{- range $key, $value := .Values.config }}

  {{ $key }}: {{ $value | quote }}

{{- end }}
