apiVersion: v1
kind: Secret
metadata:
  name: {{ include "employee-api.name" . }}-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret }}

  {{ $key }}: {{ $value | quote }}

{{- end }}