apiVersion: v1
kind: Service
metadata:
  name: {{ include "employee-api.name" . }}-svc
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "employee-api.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.container.port }}
    protocol: TCP