image:
  repository: yadavprashant510/employee-api
  tag: "74c94143a30ec1d9e5486b9dcb6751175548814e"

environment: prod
namespace:
  name: prod-employee-ns
replicaCount: 3
ingress:
  host: employee-prod.local
