image:
  repository: yadavprashant510/employee-api
  tag: "6806754cc167d97bcb3dc55b8e21e4a3a6c9b0a6"

environment: prod
namespace:
  name: prod-employee-ns
replicaCount: 3
ingress:
  host: employee-prod.local
