apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: dev-employee-api
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/yadavprashant510/employee-platform.git
    targetRevision: main
    path: helm/employee-api

    helm:
      releaseName: dev-employee-api
      valueFiles:
        - values.yaml
        - ../../environments/dev/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: dev-employee-ns

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true