apiVersion: v2
name: employee-api
description: Helm chart for Employee API
type: application

version: 0.1.0

appVersion: "1.0.0"

keywords:
  - flask
  - kubernetes
  - helm

home: https://github.com/<your-github>/employee-api

maintainers:
  - name: Prashant