image:
  repository: yadavprashant510/employee-api
  tag: "6806754cc167d97bcb3dc55b8e21e4a3a6c9b0a6"
replicaCount: 1
ingress:
  host: employee-dev.local
environment: dev
namespace:
  name: dev-employee-ns
autoscaling:
  enabled: false
