image:
  repository: yadavprashant510/employee-api
  tag: "0b717e83ebf19b9738da3206949535b82ddb50a8"
replicaCount: 1
ingress:
  host: employee-dev.local
environment: dev
namespace:
  name: dev-employee-ns
autoscaling:
  enabled: false
