image:
  repository: yadavprashant510/employee-api
  tag: "74c94143a30ec1d9e5486b9dcb6751175548814e"
replicaCount: 1
ingress:
  host: employee-dev.local
environment: dev
namespace:
  name: dev-employee-ns
autoscaling:
  enabled: false
